/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface ETag {
        /**
          * * desc is the description of the tag
         */
        "desc": string;
        "image": string;
        /**
          * * imageUrl is the url to the Image for the tag opened
         */
        "imageUrl": string;
        /**
          * * price is the price of the product in the tag
         */
        "price": number | string;
        /**
          * * xPos is the coordinate of Horizontal Axis
         */
        "xPos": number | string;
        /**
          * * yPos is the coordinate of Vertical Axis
         */
        "yPos": number | string;
    }
}
declare global {
    interface HTMLETagElement extends Components.ETag, HTMLStencilElement {
    }
    var HTMLETagElement: {
        prototype: HTMLETagElement;
        new (): HTMLETagElement;
    };
    interface HTMLElementTagNameMap {
        "e-tag": HTMLETagElement;
    }
}
declare namespace LocalJSX {
    interface ETag {
        /**
          * * desc is the description of the tag
         */
        "desc"?: string;
        "image"?: string;
        /**
          * * imageUrl is the url to the Image for the tag opened
         */
        "imageUrl"?: string;
        /**
          * * price is the price of the product in the tag
         */
        "price"?: number | string;
        /**
          * * xPos is the coordinate of Horizontal Axis
         */
        "xPos"?: number | string;
        /**
          * * yPos is the coordinate of Vertical Axis
         */
        "yPos"?: number | string;
    }
    interface IntrinsicElements {
        "e-tag": ETag;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "e-tag": LocalJSX.ETag & JSXBase.HTMLAttributes<HTMLETagElement>;
        }
    }
}
