/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface ETag {
        /**
          * * desc is the description of the tag
         */
        "desc": string;
        "image": string;
        /**
          * * imageUrl is the url to the Image for the tag opened
         */
        "imageUrl": string;
        /**
          * * price is the price of the product in the tag
         */
        "price": number | string;
        /**
          * * xPos is the coordinate of Horizontal Axis
         */
        "xPos": number | string;
        /**
          * * yPos is the coordinate of Vertical Axis
         */
        "yPos": number | string;
    }
    interface EWrapper {
        "apikey"?: string;
        "showTag": (e: any) => Promise<void>;
        "tags"?: string[];
        "videoPlayer"?: HTMLElement;
    }
}
export interface EWrapperCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLEWrapperElement;
}
declare global {
    interface HTMLETagElement extends Components.ETag, HTMLStencilElement {
    }
    var HTMLETagElement: {
        prototype: HTMLETagElement;
        new (): HTMLETagElement;
    };
    interface HTMLEWrapperElement extends Components.EWrapper, HTMLStencilElement {
    }
    var HTMLEWrapperElement: {
        prototype: HTMLEWrapperElement;
        new (): HTMLEWrapperElement;
    };
    interface HTMLElementTagNameMap {
        "e-tag": HTMLETagElement;
        "e-wrapper": HTMLEWrapperElement;
    }
}
declare namespace LocalJSX {
    interface ETag {
        /**
          * * desc is the description of the tag
         */
        "desc"?: string;
        "image"?: string;
        /**
          * * imageUrl is the url to the Image for the tag opened
         */
        "imageUrl"?: string;
        /**
          * * price is the price of the product in the tag
         */
        "price"?: number | string;
        /**
          * * xPos is the coordinate of Horizontal Axis
         */
        "xPos"?: number | string;
        /**
          * * yPos is the coordinate of Vertical Axis
         */
        "yPos"?: number | string;
    }
    interface EWrapper {
        "apikey"?: string;
        "onShowTags"?: (event: EWrapperCustomEvent<any>) => void;
        "tags"?: string[];
        "videoPlayer"?: HTMLElement;
    }
    interface IntrinsicElements {
        "e-tag": ETag;
        "e-wrapper": EWrapper;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "e-tag": LocalJSX.ETag & JSXBase.HTMLAttributes<HTMLETagElement>;
            "e-wrapper": LocalJSX.EWrapper & JSXBase.HTMLAttributes<HTMLEWrapperElement>;
        }
    }
}
